# Generated by Django 5.2.7 on 2025-11-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('input_file', models.CharField(blank=True, max_length=255)),
                ('result_file', models.CharField(blank=True, max_length=255)),
                ('accuracy', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
